#!/usr/bin/env bash
set -e

echo "Building FFmpeg WebAssembly Transcoder..."

# Build the WebAssembly module
# This will trigger build.rs which compiles FFmpeg
wasm-pack build --target web

echo "Setting up distribution files..."

# Prepare the static files
mkdir -p dist
cp -r static/* dist/
cp -r pkg dist/

# If there are any special files generated by build.rs, ensure they're copied
# The build.rs script should copy FFmpeg WebAssembly files to static/
# so they should already be included when copying static/*

echo "Starting local server..."

# Start a local server
simple-http-server dist/

echo "Server running at http://localhost:8000"
